apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-nodelink-controller
  namespace: openshift-machine-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dev-nodelink-controller
  template:
    metadata:
      labels:
        app: dev-nodelink-controller
    spec:
      containers:
      - args:
        - --logtostderr=true
        - --v=3
        - --leader-elect=true
        - --leader-elect-lease-duration=120s
        - --namespace=openshift-machine-api
        command:
        - /nodelink-controller
        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev
        imagePullPolicy: IfNotPresent
        name: nodelink-controller
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      serviceAccountName: machine-api-controllers
status: {}
