// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudscale-ch/cloudscale-go-sdk/v6 (interfaces: VolumeService)
//
// Generated by this command:
//
//	mockgen -destination=./csmock/volume_service.go -package csmock github.com/cloudscale-ch/cloudscale-go-sdk/v6 VolumeService
//

// Package csmock is a generated GoMock package.
package csmock

import (
	context "context"
	reflect "reflect"

	backoff "github.com/cenkalti/backoff/v5"
	cloudscale "github.com/cloudscale-ch/cloudscale-go-sdk/v6"
	gomock "go.uber.org/mock/gomock"
)

// MockVolumeService is a mock of VolumeService interface.
type MockVolumeService struct {
	ctrl     *gomock.Controller
	recorder *MockVolumeServiceMockRecorder
	isgomock struct{}
}

// MockVolumeServiceMockRecorder is the mock recorder for MockVolumeService.
type MockVolumeServiceMockRecorder struct {
	mock *MockVolumeService
}

// NewMockVolumeService creates a new mock instance.
func NewMockVolumeService(ctrl *gomock.Controller) *MockVolumeService {
	mock := &MockVolumeService{ctrl: ctrl}
	mock.recorder = &MockVolumeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolumeService) EXPECT() *MockVolumeServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVolumeService) Create(ctx context.Context, createRequest *cloudscale.VolumeRequest) (*cloudscale.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, createRequest)
	ret0, _ := ret[0].(*cloudscale.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVolumeServiceMockRecorder) Create(ctx, createRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVolumeService)(nil).Create), ctx, createRequest)
}

// Delete mocks base method.
func (m *MockVolumeService) Delete(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVolumeServiceMockRecorder) Delete(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVolumeService)(nil).Delete), ctx, resourceID)
}

// Get mocks base method.
func (m *MockVolumeService) Get(ctx context.Context, resourceID string) (*cloudscale.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceID)
	ret0, _ := ret[0].(*cloudscale.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVolumeServiceMockRecorder) Get(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVolumeService)(nil).Get), ctx, resourceID)
}

// List mocks base method.
func (m *MockVolumeService) List(ctx context.Context, modifiers ...cloudscale.ListRequestModifier) ([]cloudscale.Volume, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range modifiers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]cloudscale.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVolumeServiceMockRecorder) List(ctx any, modifiers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, modifiers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVolumeService)(nil).List), varargs...)
}

// Update mocks base method.
func (m *MockVolumeService) Update(ctx context.Context, resourceID string, updateRequest *cloudscale.VolumeRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resourceID, updateRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVolumeServiceMockRecorder) Update(ctx, resourceID, updateRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVolumeService)(nil).Update), ctx, resourceID, updateRequest)
}

// WaitFor mocks base method.
func (m *MockVolumeService) WaitFor(ctx context.Context, resourceID string, condition func(*cloudscale.Volume) (bool, error), opts ...backoff.RetryOption) (*cloudscale.Volume, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, resourceID, condition}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WaitFor", varargs...)
	ret0, _ := ret[0].(*cloudscale.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitFor indicates an expected call of WaitFor.
func (mr *MockVolumeServiceMockRecorder) WaitFor(ctx, resourceID, condition any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, resourceID, condition}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitFor", reflect.TypeOf((*MockVolumeService)(nil).WaitFor), varargs...)
}
